#!/bin/bash
JAR_FILE=$(find ./target -type f -iname "skoop-server-*.jar")
docker build -t tsystemsmms/skoop-server:latest --build-arg JAR_FILE=$JAR_FILE .
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push tsystemsmms/skoop-server:latest
