#!/bin/bash
JAR_FILE=$(find ./target -type f -iname "skoop-server-*.jar")
docker build -t skoop-server:latest --build-arg JAR_FILE=$JAR_FILE .
docker tag skoop-server:latest $DOCKER_USERNAME/skoop-server:latest
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push $DOCKER_USERNAME/skoop-server:latest
