= MySkills Server
Georg Wittberger <georg.wittberger@gmail.com>
v0.0.1, 2018-08-28

A lightweight web application to capture, manage and analyze skills of users and help them improve their capabilities by connecting them with each other and assisting with personalized suggestions for coaches, trainings, projects and many more.

== INCUBATION WARNING

*This project is in the incubation stage and is by far NOT ready for production use!*

== Getting started

=== Introduction

MySkills Server is a Java web application implementing the backend of the MySkills ecosystem. This server has no graphical user interface. It exposes a REST API to allow clients (e.g. the _MySkills WebApp_) to interact with the various MySkills functionalities via network. The server takes care of persistently storing the data of the MySkills domain model in a separate database.

=== System requirements

For running the application using the executable JAR file:

* Java Runtime Environment 10 (version 11 not tested so far)
* Neo4j Community Edition 3.3.x

For running the application as a Docker container:

* Docker 18.06 (or higher)
* _Optional:_ Docker Compose

For development:

* Java Development Kit 10 (version 11 not tested so far)
* Neo4j Community Edition 3.3.x
* _Optional:_ Docker 18.06 (or higher), useful for setting up a Neo4j database

=== Building the application from source

The project uses https://gradle.org/[Gradle] as the build tool. Run the following command in the project root to build the application:

    gradlew build

The final executable JAR file is produced in the `build/libs` directory.

*Tip:* If you are using a proxy you should create a gradle.properties in your home directory ($HOME), and set below properties:
```
systemProp.http.proxyHost=hostname
systemProp.http.proxyPort=8080
systemProp.http.proxyUser=username
systemProp.http.proxyPassword=xxx
systemProp.https.proxyHost=hostname
systemProp.https.proxyPort=8080
systemProp.https.proxyUser=username
systemProp.https.proxyPassword=xxx
```

=== Running the executable JAR file

After completing the Gradle build you can run the MySkills Server like a simple Java application:

    java -jar build/libs/myskills-server-0.0.1-SNAPSHOT.jar

=== Running as Docker container

We do not offer public Docker images at the moment but you can create your own after completing the Gradle build. Run the following command in the project root (mind the dot at the end):

    docker build --tag myskills/server:latest --build-arg JAR_FILE=build/libs/myskills-server-0.0.1-SNAPSHOT.jar .

Then you can start the container as usual:

    docker run --name myskills --rm -p 8080:8080 myskills/server:latest

=== Testing the setup

Once the application has started the API documentation should be available at http://localhost:8080/swagger-ui.html

== Development

=== Call for contributors

Become a contributor to MySkills by joining our KnowledgeAssets organization! Everyone can help, from UX designer over software developers and testers to documentation writers. Get involved and be part of a great community project!

Interested? Contact georg.wittberger (at) gmail.com

=== Technology overview

As described in the introduction the MySkills Server is a pure server application with no graphical user interface. The project makes use of the following noteworthy frameworks:

* https://spring.io/projects/spring-boot[Spring Boot]: Provides the basis for the Java web application. Within the application itself it faciliates the configuration of the Spring application context. Furthermore, we use the Spring Boot Gradle plugin to build the executable JAR file including an embedded Tomcat server.
* https://spring.io/projects/spring-framework[Spring Web MVC]: The REST API provided by the application is implemented using Spring Web MVC controllers. We use that synchronous variant instead of WebFlux at the moment.
* https://spring.io/projects/spring-security[Spring Security]: Provides the authentication and authorization, including access control for the REST endpoints.
* https://neo4j.com/[Neo4j]: We use this graph database to store the current state of the domain model and to obtain insights in the network of relationships between users, skills and more domain objects. The Neo4j database is typically connected to the application by the Bolt driver which is auto-configured by Spring Boot. For test automation there is also the embedded driver in the project setup.
* https://projects.spring.io/spring-data-neo4j/[Spring Data Neo4j]: The graph database is accessed via Spring Data repositories and Spring Transaction handles the transaction management. Most of this data access layer is also auto-configured by Spring Boot.
* http://springfox.github.io/springfox/[Springfox]: Provides the auto-generated Swagger UI with the REST API documentation.
* https://junit.org/junit5/[JUnit 5] and Spring Test support are used to implement automated tests for different slices of the application. Neo4j repository tests are supported by an embedded Neo4j database.

=== Setting up the Neo4j database

MySkills Server requires a https://neo4j.com/[Neo4j] database for persistent storage.

Option 1: You can download the database server https://neo4j.com/download-center/#releases[directly from the website] and install it on your system.

Option 2: You can start Neo4j as a Docker container.

* In windows:

    docker run --name neo4j -d -p 7474:7474 -p 7687:7687 -v C:\Develop\workspace\neo4j\data:/data -e NEO4J_AUTH=none neo4j:3.3

* In Linux:

    docker run --name neo4j -d -p 7474:7474 -p 7687:7687 -v $HOME/neo4j/data:/data -e NEO4J_AUTH=none neo4j:3.3

This will create a container named `neo4j` which you start/stop simply like this:

    docker start neo4j

    docker stop neo4j

_Note: During development we can start the database without any authentication enabled. So, we do not have to provide credentials in our application configuration._

=== Configuring annotation processors

The source code makes use of https://projectlombok.org/[Lombok] annotations to generate getters, setters, etc. in POJO classes. The build process takes care of processing these annotations at compile time but any IDE may require further configuration to make internal builds work.

For IntelliJ IDEA:

* Install the https://plugins.jetbrains.com/plugin/6317-lombok-plugin[Lombok Plugin]
* Open the project settings, navigate to `Build, Execution, Deployment > Compiler > Annotation Processors` and activate the checkbox `Enable annotation processing`.

=== Running the application from the IDE

You can run the application by using the Java class `io.knowledgeassets.myskills.server.MySkillsServerApplication` as main class in a usual Java launch configuration.

For example, in IntelliJ IDEA right-click on this class and select `Run 'MySkillsServer....main()'` from the context menu.

=== Configuring a different HTTP port

In case you should have to use another HTTP port than 8080 you can pass the following application argument in the launch configuration to specify a custom port:

    --server.port=1234

=== Configuring test users

MySkills Server requires an external OpenID Connect provider to generate ID token which can be used to authorize API requests.

During development a local https://www.keycloak.org/[KeyCloak] server is recommended to manage test users and create ID token.

Option 1: You can download KeyCloak https://www.keycloak.org/downloads.html[directly from the website] and install it on your system.

Option 2: You can start KeyCloak as a Docker container.

    docker run --name keycloak -d -p 9000:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin jboss/keycloak:4.3.0.Final

This will create a container named `keycloak` which you start/stop simply like this:

    docker start keycloak

    docker stop keycloak

There is an export of a suitable test realm in `tools/keycloak/myskills-realm.json` which can be imported into the KeyCloak server. The realm comes with a preconfigured client for MySkills but contains no test users. You have to create users manually within the `MySkills` realm.

In order to obtain an ID token you must call the following URL in your browser (assuming that KeyCloak listens on port 9000):

http://localhost:9000/auth/realms/MySkills/protocol/openid-connect/auth?client_id=myskills&response_type=id_token&scope=openid+profile&nonce=123&redirect_uri=http://localhost:4200/

After logging in you will be redirected to http://localhost:4200/ with the ID token passed in the `id_token` query parameter. You can copy this token and use it to authorize API requests by sending an `Authorization` header:

    Authorization: Bearer <ID token>

_Note: The default configuration of MySkills Server assumes that the KeyCloak server is available at `localhost:9000` and contains a realm named `MySkills`._

=== Testing the application

In order to execute the automated tests run the following command in the project root:

    gradlew test

The test report can be found in the `/build/reports/tests/test` directory.

The test coverage report can be generated by running this additional command:

    gradlew jacocoTestReport

The coverage report can be found in the `/build/reports/jacoco/test/html` directory.

=== Exploring the API

Open the Swagger UI of the running application: http://localhost:8080/swagger-ui.html

=== Architecture overview

Fundamentally, the MySkills Server is based on the conventions of the https://spring.io/projects/spring-boot[Spring Boot] framework. If you are familiar with that framework you should have an easy start with the project.

==== Source code structure

The base package `io.knowledgeassets.myskills.server` contains several sub-packages with focus on specific parts of the domain model. For example, `io.knowledgeassets.myskills.server.skill` contains everything related to skills as a domain object, including entity classes, data repositories, service implementations and controllers for the corresponding REST API.

_A basic design principle of MySkills Server is the application of the CQRS pattern (Command Query Responsibility Segregation)._

In short words, all read access to the domain model is strictly separated from the write access. This segregation is made explicit by the separate `command` and `query` packages inside each domain package. For example:

* `io.knowledgeassets.myskills.server.skill.command`: Contains all the code dedicated to modifications of skills
** Service implementation with methods representing the commands which alter the state of the domain model
** Controller implementation which provides POST, PUT and DELETE operations to modify the domain model
* `io.knowledgeassets.myskills.server.skill.query`: Contains all the code dedicated to reading skills
** Service implementation with methods to lookup domain objects and compile different views on the domain model
** Controller implementation which provides GET operations to request views on the domain model

_Important rule: Code from the `command` package may use code from the `query` package, e.g. to perform validation. But under no circumstances is the code in the `query` package allowed to use code from the `command` package!_

==== Authentication and authorization

The https://spring.io/projects/spring-security[Spring Security] framework is used to implement user authentication and access control for the provided API resources.

The application is implemented as a stateless OAuth2 resource server. Each API request must be authorized by including an `Authorization` header with a valid ID token:

    Authorization: Bearer <ID token>

The signature of the ID token is validated using the public key of the authorization server (offline validation). By default, this public key is automatically loaded on startup from the JWK set URI of the authorization server.

== License

https://opensource.org/licenses/MIT[MIT]
